### ISSUE TITLE
Error running initialise-repo.sh: missing start-webspoon.sh

### ISSUE THREAD

**Issue by mef** [diethardsteiner/pentaho-standardised-git-repo-setup#6]
Hi,

One step in initialise-repo.sh fails, showing the following error message:

    cp: cannot stat '/h/git-repos/pentaho-standardised-git-repo-setup/artefacts/utilities/start-webspoon.sh': No such file or directory

`start-webspoon.sh` looks to be indeed missing from the repository...

This happened when running the following command:

     $PSGRS_HOME/initialise-repo.sh  -a 1 -g enterpriseDataWarehouse -p EDW -e dev -s file-repo

P.S. thanks for creating this tool, helpful to implement good practices. Might use it for a client's project.

**Comment by diethardsteiner** [comment]
Thanks for reporting this. I just tried to fix it.
